### ISSUE TITLE
Docker Files

### ISSUE THREAD

**Issue by penguineer** [netz39/netz39fees#20]
Da es keine direkte Unterstützung für die fees im Paket-Management unserer verwendeten Distribution gibt, wären Docker-Files (Containerbeschreibungen und Compose) für ein einfaches Deployment sehr hilfreich.

Das kann gleichzeitig eine einfache Dokumentation für das Deployment sein.

**Comment by apfohl** [comment]
Ja, definitiv. Ich hab erfahrung mit Docker und könnte das mal umsetzen. Vielleicht schaffe ich das auch heute Abend. https://github.com/apfohl/PowerDNSAdminPanel wird ja auch so deployt.

**Comment by apfohl** [comment]
Ich hab mal angefangen -> #21

**Comment by LeSpocky** [comment]
Label **blocker** gesetzt, weil das effektiv das dist-upgrade der VM blockiert, auf der das im Moment läuft. Mit anderen Worten: wir wollen das nach Docker umziehen, damit wir mit der VM weiter kommen.

**Comment by apfohl** [comment]
Da ist doch bereits #21... das ist easy fertig zu machen.

**Comment by okirmis** [comment]
Siehe auch PR #23, das basiert darauf

**Comment by okirmis** [comment]
@penguineer und @LeSpocky: Da PR #23 jetzt durch ist, kann das Issue geschlossen werden, oder spricht aus eurer Sicht noch etwas dagegen?

**Comment by LeSpocky** [comment]
Grundsätzlich spricht nichts dagegen. Ich schlage vor wir schließen das Ticket hier, wenn wir die neue Variante in production deployed haben?

**Comment by penguineer** [comment]
Hier geht es um die Entwicklung der grundsätzlichen Funktionalität → das Ticket sollte offen bleiben, bis das sicher geklärt ist.
